-- Supabase Database Schema for Portfolio Website

-- 1. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    content TEXT,
    image TEXT,
    github TEXT,
    demo TEXT,
    tags TEXT[],
    color TEXT DEFAULT '#8B5CF6',
    "order" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Skills Table
CREATE TABLE IF NOT EXISTS public.skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level INTEGER DEFAULT 0,
    category TEXT, -- e.g., 'Frontend', 'Backend', 'Tools'
    "order" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Experience Table
CREATE TABLE IF NOT EXISTS public.experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT,
    period TEXT,
    description TEXT,
    "order" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Education Table
CREATE TABLE IF NOT EXISTS public.education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree TEXT NOT NULL,
    institution TEXT,
    period TEXT,
    description TEXT,
    color TEXT DEFAULT '#10B981',
    "order" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Messages Table (Contact Form)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    subject TEXT,
    message TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Settings Table (Global Configuration)
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT PRIMARY KEY DEFAULT 1, -- Usually only one row with id=1
    site_name TEXT,
    name TEXT,
    title TEXT,
    bio TEXT,
    career_objective TEXT,
    github_url TEXT,
    linkedin_url TEXT,
    email TEXT,
    profile_image_url TEXT,
    cv_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Initialize Settings (Optional: adds a default row for site data)
INSERT INTO public.settings (id, site_name, name, title)
VALUES (1, 'My Portfolio', 'Admin User', 'Full Stack Developer')
ON CONFLICT (id) DO NOTHING;

-- Enable Row Level Security (RLS) - Optional but recommended
-- ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
-- (Add policies as needed for production security)
